server:
  port: 30000
spring:
  application:
    name: portal
  profiles:
    include: seata
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: SEATA_GROUP
        cluster-name: default
