server:
  port: 30002
spring:
  application:
    name: store
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ing_seata_store?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

