server:
  port: 30001
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ing_seata_demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

